
package webmini1.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.7
 * Mon Jan 15 22:13:20 HKT 2024
 * Generated source version: 3.5.7
 */

@XmlRootElement(name = "getTouristInfoResponse", namespace = "http://www.webmini1")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTouristInfoResponse", namespace = "http://www.webmini1")

public class GetTouristInfoResponse {

    @XmlElement(name = "return")
    private String[] _return;

    public String[] getReturn() {
        return this._return;
    }

    public void setReturn(String[] new_return)  {
        this._return = new_return;
    }

}

