
package webmini1.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.7
 * Mon Jan 15 22:13:20 HKT 2024
 * Generated source version: 3.5.7
 */

@XmlRootElement(name = "getTouristInfo", namespace = "http://www.webmini1")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTouristInfo", namespace = "http://www.webmini1")

public class GetTouristInfo {


}

